AEC_DATA_DIR = "/home/jonahmc2/data/AEC/new_AEC-Challenge/"
RES_DATA_DIR = "/mnt/data/junkai2/"
RIR_DATA_DIR = "/home/jonahmc2/data/AEC/RIRS_NOISES/"
EQ_DATA_DIR = "/home/jonahmc2/data/daps/"
REVERB_DATA_DIR = "/home/jonahmc2/data/LDC_mod/REVERB_DATA_OFFICIAL"
CHIME3_DATA_DIR = "/home/jonahmc2/data/LDC_mod/CHiME3_norm_speech_noise"
